title: Arduino Synth
hero_image: images/banner.png
description: Create an Arduino-powered 8-bit synth
theme: blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: 
technologies: 
site_areas: hackspace
steps:
  - title: Introduction
  - title: What you will need
  - title: Sinewave
  - title: How it works
  - title: Making adjustments
  - title: More control