---
title: Arduino Synth
hero_image: images/banner.png
description: Create an Arduino-powered 8-bit synth
theme: blue
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: ''
technologies: ''
site_areas: HackSpace
steps:
- title: Introduction
- title: What you will need
- title: Sine wave
- title: How it works
- title: Making adjustments
- title: More control
